<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item code_js-sku-input-field js-quick-order-qty form-control newRow text-left</name>
   <tag></tag>
   <elementGuidId>ba6ed749-76c4-4e0a-bd09-ea53fbeace91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.js-sku-input-field.js-quick-order-qty.form-control.newRow.text-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter code</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-sku-input-field js-quick-order-qty form-control newRow text-left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quickOrder&quot;)/div[@class=&quot;account-section-content cartPresentation&quot;]/div[@class=&quot;js-quick-order-container sticky-content&quot;]/ul[@class=&quot;js-ul-container table-ui2 table-ui2-striped table-ui2-layout1 table-ui2-layout1-icons table-ui2-quickOrder marginB20&quot;]/li[@class=&quot;item-list-item table-tr js-li-container&quot;]/div[@class=&quot;js-sku-container table-td width-full-xs table-xs-padding marginB10-xs&quot;]/div[@class=&quot;form-horizontal clearfix&quot;]/div[@class=&quot;control-field table-xs-9&quot;]/input[@class=&quot;js-sku-input-field js-quick-order-qty form-control newRow text-left&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quickOrder']/div/div[3]/ul/li[2]/div/div/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
